version: "3.5"

services:
  update_mappping_keeper:
    build: .
    image: &app app
    restart: always
    env_file: &envfile
      - .env
    command: bash -c "python -u network_load.py && python -u keeper.py --bot update_oneCT_accounts"
    volumes:
      - ./app:/home/app/web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  # close_keeper:
  #     build: .
  #     image: &app app
  #     restart: always
  #     env_file: &envfile
  #         - .env
  #     command: bash -c "python -u network_load.py && python -u keeper.py --bot close"
  #     volumes:
  #         - ./app:/home/app/web
  #     logging:
  #         driver: "json-file"
  #         options:
  #             max-size: "10m"
  #             max-file: "3"
  # update_keeper:
  #     build: .
  #     image: *app
  #     restart: always
  #     env_file: *envfile
  #     command: bash -c "python -u network_load.py && python -u keeper.py --bot update"
  #     volumes:
  #         - ./app:/home/app/web
  #     logging:
  #         driver: "json-file"
  #         options:
  #             max-size: "10m"
  #             max-file: "3"
  # open_keeper:
  #     build: .
  #     image: *app
  #     restart: always
  #     env_file: *envfile
  #     command: bash -c "python -u network_load.py && python -u keeper.py --bot open"
  #     volumes:
  #         - ./app:/home/app/web
  #     logging:
  #         driver: "json-file"
  #         options:
  #             max-size: "10m"
  #             max-file: "3"
volumes:
  static_volume:
  data:
